# Generated by Django 4.2.29 on 2026-03-18 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='agentes/')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(max_length=20, verbose_name='RG')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone / Contato')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('cnh', models.CharField(blank=True, max_length=20, verbose_name='CNH')),
                ('cnh_validade', models.DateField(blank=True, null=True, verbose_name='Val. CNH')),
                ('cnh_categoria', models.CharField(blank=True, default='B', max_length=5, verbose_name='Categoria CNH')),
                ('cnv', models.CharField(blank=True, max_length=20, verbose_name='CNV')),
                ('cnv_validade', models.DateField(blank=True, null=True, verbose_name='Val. CNV')),
                ('cert_armamento_validade', models.DateField(blank=True, null=True, verbose_name='Val. Cert. Armamento')),
                ('funcao', models.CharField(choices=[('agente_escolta', 'Agente de Escolta'), ('motorista_escolta', 'Motorista Escolta'), ('supervisor', 'Supervisor'), ('coordenador', 'Coordenador')], default='agente_escolta', max_length=30, verbose_name='Função')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('afastado', 'Afastado'), ('inativo', 'Inativo')], default='ativo', max_length=15, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agente',
                'verbose_name_plural': 'Agentes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=200, verbose_name='Razão Social')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=30, verbose_name='IE / IM')),
                ('endereco', models.CharField(blank=True, max_length=300, verbose_name='Endereço')),
                ('cidade_uf', models.CharField(blank=True, max_length=100, verbose_name='Cidade / UF')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('solicitante_nome', models.CharField(max_length=200, verbose_name='Nome do Solicitante')),
                ('solicitante_cargo', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('telefone', models.CharField(max_length=20, verbose_name='Tel / Nextel')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('tipo_contrato', models.CharField(choices=[('escolta_armada', 'Escolta armada'), ('vigilancia_patrimonial', 'Vigilância patrimonial'), ('escolta_eventual', 'Escolta eventual')], default='escolta_armada', max_length=30, verbose_name='Tipo de Contrato')),
                ('rota_padrao', models.TextField(blank=True, verbose_name='Rota / Trajeto padrão')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('negociacao', 'Em negociação')], default='ativo', max_length=15, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['razao_social'],
            },
        ),
        migrations.CreateModel(
            name='Viatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
                ('marca_modelo', models.CharField(max_length=100, verbose_name='Marca / Modelo')),
                ('ano', models.CharField(max_length=4, verbose_name='Ano')),
                ('cor', models.CharField(max_length=50, verbose_name='Cor')),
                ('placa', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('frota', models.CharField(blank=True, max_length=20, verbose_name='Código de Frota')),
                ('mct_id', models.CharField(blank=True, max_length=20, verbose_name='MCT / ID')),
                ('renavam', models.CharField(blank=True, max_length=15, verbose_name='RENAVAM')),
                ('chassi', models.CharField(blank=True, max_length=30, verbose_name='Chassi')),
                ('crlv_validade', models.DateField(blank=True, null=True, verbose_name='CRLV Vencimento')),
                ('seguro_validade', models.DateField(blank=True, null=True, verbose_name='Seguro Vencimento')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('manutencao', 'Em manutenção'), ('inativa', 'Inativa')], default='ativa', max_length=15, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Viatura',
                'verbose_name_plural': 'Viaturas',
                'ordering': ['placa'],
            },
        ),
        migrations.CreateModel(
            name='Rastreador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca / Fabricante')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('numero_serie', models.CharField(max_length=50, unique=True, verbose_name='Nº de Série')),
                ('imei', models.CharField(blank=True, max_length=20, verbose_name='IMEI')),
                ('chip_sim', models.CharField(blank=True, max_length=30, verbose_name='Chip / SIM')),
                ('operadora', models.CharField(blank=True, choices=[('Claro', 'Claro'), ('Vivo', 'Vivo'), ('TIM', 'TIM'), ('Oi', 'Oi')], max_length=10, verbose_name='Operadora')),
                ('central_monitoramento', models.CharField(blank=True, max_length=100, verbose_name='Central de Monitoramento')),
                ('data_instalacao', models.DateField(blank=True, null=True, verbose_name='Data de Instalação')),
                ('validade_contrato', models.DateField(blank=True, null=True, verbose_name='Validade Contrato')),
                ('login_plataforma', models.CharField(blank=True, max_length=100, verbose_name='Login Plataforma')),
                ('status', models.CharField(choices=[('online', 'Ativo / Online'), ('offline', 'Offline'), ('manutencao', 'Em manutenção')], default='online', max_length=15, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('viatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rastreadores', to='cadastros.viatura', verbose_name='Viatura vinculada')),
            ],
            options={
                'verbose_name': 'Rastreador',
                'verbose_name_plural': 'Rastreadores',
                'ordering': ['marca', 'modelo'],
            },
        ),
        migrations.CreateModel(
            name='Armamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pistola', 'Pistola'), ('revolver', 'Revólver'), ('espingarda', 'Espingarda'), ('rifle', 'Rifle')], max_length=20, verbose_name='Tipo')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca / Fabricante')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('calibre', models.CharField(max_length=20, verbose_name='Calibre')),
                ('numero_serie', models.CharField(max_length=50, unique=True, verbose_name='Nº de Série')),
                ('numero_cano', models.CharField(blank=True, max_length=50, verbose_name='Nº do Cano')),
                ('registro_cr', models.CharField(blank=True, max_length=50, verbose_name='Registro CR/SINARM')),
                ('registro_validade', models.DateField(blank=True, null=True, verbose_name='Val. Registro')),
                ('data_aquisicao', models.DateField(blank=True, null=True, verbose_name='Data de Aquisição')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('em_uso', 'Em uso / Operação'), ('manutencao', 'Manutenção'), ('apreendida', 'Apreendida')], default='disponivel', max_length=15, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('agente_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='armamentos', to='cadastros.agente', verbose_name='Agente Responsável')),
            ],
            options={
                'verbose_name': 'Armamento',
                'verbose_name_plural': 'Armamentos',
                'ordering': ['tipo', 'marca'],
            },
        ),
    ]
