# Generated by Django 4.2.29 on 2026-03-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_os_operacional_veiculos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agente',
            name='funcao',
            field=models.CharField(choices=[('agente_escolta', 'Agente de Escolta'), ('motorista_escolta', 'Motorista Escolta'), ('supervisor', 'Supervisor'), ('coordenador', 'Coordenador')], default='agente_escolta', max_length=30, verbose_name='Funcao'),
        ),
        migrations.AlterField(
            model_name='agente',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observacoes'),
        ),
        migrations.AlterField(
            model_name='armamento',
            name='data_aquisicao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Aquisicao'),
        ),
        migrations.AlterField(
            model_name='armamento',
            name='numero_cano',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nr do Cano'),
        ),
        migrations.AlterField(
            model_name='armamento',
            name='numero_serie',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nr de Serie'),
        ),
        migrations.AlterField(
            model_name='armamento',
            name='tipo',
            field=models.CharField(choices=[('pistola', 'Pistola'), ('revolver', 'Revolver'), ('espingarda', 'Espingarda'), ('rifle', 'Rifle')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(blank=True, max_length=300, verbose_name='Endereco'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='razao_social',
            field=models.CharField(max_length=200, verbose_name='Razao Social'),
        ),
        migrations.AlterField(
            model_name='rastreador',
            name='numero_serie',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nr de Serie'),
        ),
        migrations.AlterField(
            model_name='rastreador',
            name='status',
            field=models.CharField(choices=[('online', 'Ativo / Online'), ('offline', 'Offline'), ('manutencao', 'Em manutencao')], default='online', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='viatura',
            name='frota',
            field=models.CharField(blank=True, max_length=20, verbose_name='Frota'),
        ),
        migrations.AlterField(
            model_name='viatura',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observacoes'),
        ),
        migrations.AlterField(
            model_name='viatura',
            name='status',
            field=models.CharField(choices=[('ativa', 'Ativa'), ('manutencao', 'Em manutencao'), ('inativa', 'Inativa')], default='ativa', max_length=15, verbose_name='Status'),
        ),
    ]
