# Generated by Django 4.2.29 on 2026-03-25 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastros', '0015_setup_groups_and_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('developer', 'Developer'), ('admin', 'Administrador'), ('operador', 'Operador')], default='operador', max_length=20, verbose_name='Nível de Acesso')),
                ('oculto', models.BooleanField(default=False, help_text='Se marcado, não aparece em listagens de usuários', verbose_name='Usuário Oculto')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
    ]
