# Generated by Django 4.2.29 on 2026-04-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0019_osoperacional_gps'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome Fantasia'),
        ),
    ]
