# Generated by Django 4.2.29 on 2026-04-11 02:17

import cadastros.models
from django.db import migrations, models
import django.db.models.deletion


def _foto_upload_path(instance, filename):
    return f'comprovantes/{filename}'




class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0021_cliente_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DespesaOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('combustivel', 'Combustível'), ('refeicao', 'Refeição'), ('hospedagem', 'Hospedagem'), ('pedagio', 'Pedágio Avulso'), ('estacionamento', 'Estacionamento'), ('outro', 'Outro')], max_length=20, verbose_name='Tipo')),
                ('natureza', models.CharField(choices=[('despesa', 'Despesa'), ('credito', 'Crédito / Reembolso')], default='despesa', max_length=10, verbose_name='Natureza')),
                ('descricao', models.CharField(blank=True, max_length=300, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('comprovante', models.ImageField(blank=True, null=True, upload_to=_foto_upload_path, verbose_name='Comprovante (foto)')),
                ('ocorrido_em', models.DateTimeField(verbose_name='Data / Hora')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Despesa / Crédito',
                'verbose_name_plural': 'Despesas / Créditos',
                'ordering': ['ocorrido_em'],
            },
        ),
        migrations.CreateModel(
            name='TrocaMotorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motorista_saindo', models.CharField(max_length=200, verbose_name='Motorista Saindo')),
                ('motorista_entrando', models.CharField(max_length=200, verbose_name='Motorista Entrando')),
                ('ocorrido_em', models.DateTimeField(verbose_name='Data / Hora da Troca')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trocas_motorista', to='cadastros.ordemservico', verbose_name='OS')),
                ('veiculo_escoltado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trocas', to='cadastros.veiculoescoltado', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Troca de Motorista',
                'verbose_name_plural': 'Trocas de Motorista',
                'ordering': ['ocorrido_em'],
            },
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('abastecimento', 'Abastecimento'), ('refeicao', 'Refeição'), ('banheiro', 'Banheiro'), ('mecanica', 'Mecânica / Pane'), ('fiscal', 'Fiscalização / Barreira'), ('aguardando', 'Aguardando Instruções'), ('outro', 'Outro')], max_length=20, verbose_name='Motivo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição / Observações')),
                ('inicio', models.DateTimeField(verbose_name='Início da Parada')),
                ('fim', models.DateTimeField(blank=True, null=True, verbose_name='Fim da Parada')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='cadastros.ordemservico', verbose_name='OS')),
            ],
            options={
                'verbose_name': 'Parada',
                'verbose_name_plural': 'Paradas',
                'ordering': ['inicio'],
            },
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('acidente', 'Acidente de Trânsito'), ('tentativa_roubo', 'Tentativa de Roubo'), ('avaria_carga', 'Avaria na Carga'), ('pane_viatura', 'Pane / Defeito Mecânico'), ('atividade_suspeita', 'Atividade Suspeita'), ('outro', 'Outro')], max_length=30, verbose_name='Tipo')),
                ('gravidade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10, verbose_name='Gravidade')),
                ('descricao', models.TextField(verbose_name='Descrição do Incidente')),
                ('ocorrido_em', models.DateTimeField(verbose_name='Data / Hora do Incidente')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('bo_numero', models.CharField(blank=True, max_length=50, verbose_name='Nº Boletim de Ocorrência')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidentes', to='cadastros.ordemservico', verbose_name='OS')),
            ],
            options={
                'verbose_name': 'Incidente',
                'verbose_name_plural': 'Incidentes',
                'ordering': ['ocorrido_em'],
            },
        ),
        migrations.CreateModel(
            name='FotoVeiculoEscoltado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momento', models.CharField(choices=[('antes', 'Antes da Escolta'), ('depois', 'Após a Escolta'), ('outro', 'Outro')], default='antes', max_length=10)),
                ('foto', models.ImageField(upload_to=_foto_upload_path, verbose_name='Foto')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='cadastros.veiculoescoltado', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Foto de Veículo Escoltado',
                'verbose_name_plural': 'Fotos de Veículos Escoltados',
            },
        ),
        migrations.CreateModel(
            name='FotoTrocaMotorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to=_foto_upload_path, verbose_name='Foto')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('troca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='cadastros.trocamotorista', verbose_name='Troca')),
            ],
            options={
                'verbose_name': 'Foto de Troca de Motorista',
                'verbose_name_plural': 'Fotos de Troca de Motorista',
            },
        ),
        migrations.CreateModel(
            name='FotoParada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to=_foto_upload_path, verbose_name='Foto')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('parada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='cadastros.parada', verbose_name='Parada')),
            ],
            options={
                'verbose_name': 'Foto de Parada',
                'verbose_name_plural': 'Fotos de Parada',
            },
        ),
        migrations.CreateModel(
            name='FotoMarco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marco', models.CharField(choices=[('inicio_viagem', 'Início de Viagem'), ('chegada_operacao', 'Chegada Operação'), ('inicio_operacao', 'Início Operação'), ('termino_operacao', 'Término Operação'), ('termino_viagem', 'Término de Viagem')], max_length=30, verbose_name='Marco')),
                ('foto', models.ImageField(upload_to=_foto_upload_path, verbose_name='Foto')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_marcos', to='cadastros.ordemservico', verbose_name='OS')),
            ],
            options={
                'verbose_name': 'Foto de Marco',
                'verbose_name_plural': 'Fotos de Marcos',
                'ordering': ['marco', 'criado_em'],
            },
        ),
        migrations.CreateModel(
            name='FotoIncidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to=_foto_upload_path, verbose_name='Foto')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('incidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='cadastros.incidente', verbose_name='Incidente')),
            ],
            options={
                'verbose_name': 'Foto de Incidente',
                'verbose_name_plural': 'Fotos de Incidente',
            },
        ),
        migrations.CreateModel(
            name='AssinaturaOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('agente1', 'Agente 1'), ('agente2', 'Agente 2'), ('motorista', 'Motorista Escoltado'), ('supervisor', 'Supervisor')], max_length=20, verbose_name='Tipo')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Signatário')),
                ('imagem', models.ImageField(upload_to=_foto_upload_path, verbose_name='Assinatura')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='cadastros.ordemservico', verbose_name='OS')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
                'ordering': ['tipo'],
                'unique_together': {('os', 'tipo')},
            },
        ),
    ]
