# Generated by Django 4.2.29 on 2026-04-13 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0013_tabela_preco_boletim'),
        ('cadastros', '0023_despesaos_os_fk'),
    ]

    operations = [
    ]
