# Generated by Django 4.2.29 on 2026-04-13 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0023_despesaos_os_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesaos',
            name='os',
        ),
    ]
