# Generated by Django 4.2.29 on 2026-04-13 23:20

import cadastros.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0024_merge_0013_tabela_preco_boletim_0023_despesaos_os_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesaos',
            name='os',
        ),
        migrations.AlterField(
            model_name='assinaturaos',
            name='imagem',
            field=models.ImageField(upload_to=cadastros.models._foto_upload_path, verbose_name='Assinatura'),
        ),
        migrations.AlterField(
            model_name='boletimmedicao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='despesaos',
            name='comprovante',
            field=models.ImageField(blank=True, null=True, upload_to=cadastros.models._foto_upload_path, verbose_name='Comprovante (foto)'),
        ),
        migrations.AlterField(
            model_name='fotoincidente',
            name='foto',
            field=models.ImageField(upload_to=cadastros.models._foto_upload_path, verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='fotomarco',
            name='foto',
            field=models.ImageField(upload_to=cadastros.models._foto_upload_path, verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='fotoparada',
            name='foto',
            field=models.ImageField(upload_to=cadastros.models._foto_upload_path, verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='fototrocamotorista',
            name='foto',
            field=models.ImageField(upload_to=cadastros.models._foto_upload_path, verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='fotoveiculoescoltado',
            name='foto',
            field=models.ImageField(upload_to=cadastros.models._foto_upload_path, verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='tabelapreco',
            name='franquia_horas',
            field=models.CharField(default='000:00', max_length=6, verbose_name='Franquia Horas (HHH:MM)'),
        ),
        migrations.AlterField(
            model_name='tabelapreco',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
