# Generated by Django 4.2.29 on 2026-04-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0027_seed_espelhamentos_historicos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espelhamentoenviado',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
