# Generated by Django 5.2.13 on 2026-04-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0029_funcionariopatrimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='cancelada_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cancelada em'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='tipo_cancelamento',
            field=models.CharField(blank=True, choices=[('com_deslocamento', 'Com Deslocamento'), ('sem_deslocamento', 'Sem Deslocamento')], max_length=20, null=True, verbose_name='Tipo de Cancelamento'),
        ),
    ]
