# Generated by Django 5.2.13 on 2026-05-12 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0038_agente_certidao_pdfs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agente',
            name='certidao_tjdf_consultado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última consulta TJDFT'),
        ),
        migrations.AlterField(
            model_name='agente',
            name='certidao_tjdf_detalhe',
            field=models.TextField(blank=True, verbose_name='Detalhe TJDFT'),
        ),
        migrations.AlterField(
            model_name='agente',
            name='certidao_tjdf_status',
            field=models.CharField(blank=True, max_length=20, verbose_name='Certidão TJDFT'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='tipo_viagem',
            field=models.CharField(choices=[('urbana', 'Urbana'), ('rodoviaria', 'Rodoviária'), ('administrativa', 'Administrativa'), ('preservacao', 'Preservação')], max_length=20, verbose_name='Tipo de Viagem'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='nivel',
            field=models.CharField(choices=[('developer', 'Developer'), ('admin', 'Administrador'), ('operador', 'Operador'), ('financeiro', 'Financeiro')], default='operador', max_length=20, verbose_name='Nível de Acesso'),
        ),
    ]
