# Generated by Django 4.2.29 on 2026-05-20 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastros', '0039_alter_agente_certidao_tjdf_consultado_em_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14)),
                ('nome_retornado', models.CharField(blank=True, max_length=200)),
                ('status_cpf', models.CharField(blank=True, max_length=30)),
                ('total_processos', models.PositiveIntegerField(default=0)),
                ('resultado_json', models.JSONField(default=dict)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='consultas_processo/')),
                ('transaction_id', models.CharField(blank=True, max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas_processo', to='cadastros.funcionariopatrimonial')),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consulta de Processo',
                'verbose_name_plural': 'Consultas de Processos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
