# Generated by Django 4.2.29 on 2026-05-20 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0040_consultaprocesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultaprocesso',
            name='origem',
            field=models.CharField(choices=[('auto_save', 'Auto (salvamento)'), ('auto_agendado', 'Auto (agendado)'), ('manual', 'Manual')], default='manual', max_length=20),
        ),
    ]
