# Generated by Django 4.2.29 on 2026-05-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0041_consultaprocesso_origem'),
    ]

    operations = [
        migrations.AddField(
            model_name='agente',
            name='endereco',
            field=models.TextField(blank=True, default='STRC TRECHO 4, BLOCO F, LOTE 02, ZONA INDUSTRIAL - SIA, Brasília - DF, 71225-540', verbose_name='Endereço'),
        ),
    ]
