# Generated by Django 4.2.29 on 2026-05-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0042_agente_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionariopatrimonial',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome da Mãe'),
        ),
    ]
