# Generated by Django 4.2.29 on 2026-05-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0043_funcionariopatrimonial_nome_mae'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionariopatrimonial',
            name='empresa',
            field=models.CharField(choices=[('jr_seguranca', 'JR Segurança'), ('jrs_facilities', 'JRS Facilities')], default='jr_seguranca', max_length=20, verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='funcionariopatrimonial',
            name='cargo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='funcionariopatrimonial',
            name='tipo',
            field=models.CharField(blank=True, choices=[('vigilante', 'Vigilante Patrimonial'), ('porteiro', 'Porteiro'), ('brigadista', 'Brigadista')], max_length=20, verbose_name='Tipo'),
        ),
    ]
