# Generated by Django 4.2.29 on 2026-05-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0044_funcionariopatrimonial_empresa_funcionariopatrimonial_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionariopatrimonial',
            name='empresa',
            field=models.CharField(choices=[('jr_seguranca', 'JR Segurança'), ('jrs_facilities', 'JRS Facilities'), ('freelance', 'Freelance')], default='jr_seguranca', max_length=20, verbose_name='Empresa'),
        ),
    ]
