# Generated by Django 5.2.15 on 2026-09-29 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0049_cliente_token_portal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='forma_solicitacao',
            field=models.CharField(choices=[('email', 'E-mail'), ('telefone', 'Telefone'), ('whatsapp', 'WhatsApp'), ('sistema', 'Sistema (contratante)')], max_length=20, verbose_name='Forma de Solicitação'),
        ),
        migrations.AlterField(
            model_name='tabelapreco',
            name='velocidade_media',
            field=models.PositiveIntegerField(blank=True, help_text='Se preenchido, franquia de horas = KM ÷ velocidade e o excedente KM = KM total × taxa KM.', null=True, verbose_name='Velocidade Média (km/h)'),
        ),
        migrations.CreateModel(
            name='SolicitacaoEscolta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(default='SPARTACUS', max_length=60, verbose_name='Contratante')),
                ('numero_se', models.CharField(blank=True, max_length=40, verbose_name='Nº S.E. (cliente do contratante)')),
                ('numero_os_hub', models.CharField(max_length=40, verbose_name='Nº OS do contratante')),
                ('cliente_nome', models.CharField(blank=True, max_length=200, verbose_name='Cliente')),
                ('data_missao', models.DateField(blank=True, null=True, verbose_name='Data da missão')),
                ('hora_missao', models.TimeField(blank=True, null=True, verbose_name='Hora da missão')),
                ('equipes', models.CharField(blank=True, max_length=200, verbose_name='Qtde de equipes / VTR')),
                ('endereco_origem', models.CharField(blank=True, max_length=300, verbose_name='Endereço de origem')),
                ('endereco_destino', models.CharField(blank=True, max_length=300, verbose_name='Endereço de destino')),
                ('placa_veiculo', models.CharField(blank=True, max_length=20, verbose_name='Placa do veículo')),
                ('motorista', models.CharField(blank=True, max_length=200, verbose_name='Motorista')),
                ('motorista_telefone', models.CharField(blank=True, max_length=30, verbose_name='Telefone do motorista')),
                ('conta_espelhamento', models.CharField(blank=True, max_length=100, verbose_name='Conta para espelhamento')),
                ('solicitante', models.CharField(blank=True, max_length=120, verbose_name='Solicitante')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando'), ('aceita', 'Aceita'), ('recusada', 'Recusada')], default='aguardando', max_length=12, verbose_name='Situação')),
                ('motivo_recusa', models.CharField(blank=True, max_length=300, verbose_name='Motivo da recusa')),
                ('recebida_em', models.DateTimeField(auto_now_add=True)),
                ('respondida_em', models.DateTimeField(blank=True, null=True)),
                ('os', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes', to='cadastros.ordemservico', verbose_name='OS gerada')),
                ('respondida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_respondidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação de Escolta',
                'verbose_name_plural': 'Solicitações de Escolta',
                'ordering': ['-recebida_em'],
                'constraints': [models.UniqueConstraint(fields=('origem', 'numero_os_hub'), name='uniq_solicitacao_por_origem')],
            },
        ),
    ]
