# Generated by Django 4.2.29 on 2026-03-19 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_alter_agente_funcao_alter_agente_observacoes_and_more'),
        ('cadastros', '0009_status_novos'),
    ]

    operations = [
    ]
